<a href="https://colab.research.google.com/github/NOdubT/Python/blob/main/Descriptive_Analytics_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount("/content/drive")

%cd /content/drive/MyDrive/MA/data
sales_data = pd.read_csv("sales_data.csv")

Mounted at /content/drive
/content/drive/MyDrive/MA/data

3. Виведи перші 5 рядків датасету.

In [ ]:
sales_data.head()

,Order_Date,Time,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product_Category,Product,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_method
0,2018-01-01,10:11:40,5.0,29317,Male,Web,Member,Auto & Accessories,Car Media Players,140.0,4.0,0.3,43.2,4.3,Medium,e_wallet
1,2018-01-01,22:30:44,7.0,42270,Male,Web,Member,Auto & Accessories,Car Pillow & Neck Rest,231.0,5.0,0.1,139.5,13.9,High,money_order
2,2018-01-01,21:55:31,10.0,14563,Male,Web,Member,Auto & Accessories,Car Speakers,211.0,5.0,0.1,120.5,12.0,High,credit_card
3,2018-01-01,13:57:15,9.0,58601,Male,Web,Member,Auto & Accessories,Tyre,250.0,4.0,0.2,150.0,15.0,Critical,credit_card
4,2018-01-01,15:17:41,2.0,48342,Male,Web,Member,Auto & Accessories,Tyre,250.0,1.0,0.1,165.0,16.5,High,credit_card

4. Додай текстовий блок та створи заголовок «Перетворення даних». У ньому виконай роботу над стовпчиками:
- Перетвори стовпчик Order_Date на тип datetime (для перетворення Order_Date на тип datetime спочатку обʼєднай колонки дати та часу.)
- Видали стовпчик Time.
- Створи новий стовпчик sales_amount = Sales * Quantity.
- Стовпчик Gender перетвори таким чином, щоб він містив значення F та M.
- Назви стовпчиків перетвори таким чином, щоб усі літери були маленькими.

💡 Хорошою практикою є перевіряти дані після маніпуляцій. Для цього скористайся методами head() та info().

# Перетворення даних

In [ ]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Date           51290 non-null  object
 1   Time                 51290 non-null  object
 2   Aging                51289 non-null  float64
 3   Customer_Id          51290 non-null  int64
 4   Gender               51290 non-null  object
 5   Device_Type          51290 non-null  object
 6   Customer_Login_type  51290 non-null  object
 7   Product_Category     51290 non-null  object
 8   Product              51290 non-null  object
 9   Sales                51289 non-null  float64
 10  Quantity             51288 non-null  float64
 11  Discount             51289 non-null  float64
 12  Profit               51290 non-null  float64
 13  Shipping_Cost        51289 non-null  float64
 14  Order_Priority       51288 non-null  object
 15  Payment_method       51290 non-null  object
dtypes: float64(6), int64(1), object(9)
memory usage: 6.3+ MB

In [ ]:
sales_data["Order_Date"] = pd.to_datetime(sales_data["Order_Date"] + " " + sales_data["Time"], format="%Y-%m-%d %H:%M:%S")

In [ ]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Date           51290 non-null  datetime64[ns]
 1   Time                 51290 non-null  object
 2   Aging                51289 non-null  float64
 3   Customer_Id          51290 non-null  int64
 4   Gender               51290 non-null  object
 5   Device_Type          51290 non-null  object
 6   Customer_Login_type  51290 non-null  object
 7   Product_Category     51290 non-null  object
 8   Product              51290 non-null  object
 9   Sales                51289 non-null  float64
 10  Quantity             51288 non-null  float64
 11  Discount             51289 non-null  float64
 12  Profit               51290 non-null  float64
 13  Shipping_Cost        51289 non-null  float64
 14  Order_Priority       51288 non-null  object
 15  Payment_method       51290 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(8)
memory usage: 6.3+ MB

In [ ]:
sales_data.drop("Time", axis=1)

,Order_Date,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product_Category,Product,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_method
0,2018-01-01 10:11:40,5.0,29317,Male,Web,Member,Auto & Accessories,Car Media Players,140.0,4.0,0.3,43.2,4.3,Medium,e_wallet
1,2018-01-01 22:30:44,7.0,42270,Male,Web,Member,Auto & Accessories,Car Pillow & Neck Rest,231.0,5.0,0.1,139.5,13.9,High,money_order
2,2018-01-01 21:55:31,10.0,14563,Male,Web,Member,Auto & Accessories,Car Speakers,211.0,5.0,0.1,120.5,12.0,High,credit_card
3,2018-01-01 13:57:15,9.0,58601,Male,Web,Member,Auto & Accessories,Tyre,250.0,4.0,0.2,150.0,15.0,Critical,credit_card
4,2018-01-01 15:17:41,2.0,48342,Male,Web,Member,Auto & Accessories,Tyre,250.0,1.0,0.1,165.0,16.5,High,credit_card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,2018-12-30 16:20:22,5.0,88891,Male,Web,Member,Home & Furniture,Sofas,67.0,1.0,0.4,33.5,3.4,Medium,credit_card
51286,2018-12-30 11:52:02,7.0,74259,Male,Web,Member,Home & Furniture,Curtains,34.0,5.0,0.3,6.8,0.7,Medium,credit_card
51287,2018-12-30 15:06:46,5.0,62596,Male,Web,Member,Home & Furniture,Umbrellas,70.0,1.0,0.2,35.0,3.5,Medium,money_order
51288,2018-12-30 15:36:49,1.0,77349,Male,Web,Member,Home & Furniture,Dinner Crockery,133.0,1.0,0.3,49.0,4.9,Medium,credit_card
51289,2018-12-30 13:49:02,7.0,79637,Male,Web,Member,Home & Furniture,Sofa Covers,216.0,5.0,0.3,103.6,10.4,Medium,money_order

In [ ]:
sales_data["sales_amount"] = sales_data["Sales"] * sales_data["Quantity"]

In [ ]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_Date           51290 non-null  datetime64[ns]
 1   Time                 51290 non-null  object
 2   Aging                51289 non-null  float64
 3   Customer_Id          51290 non-null  int64
 4   Gender               51290 non-null  object
 5   Device_Type          51290 non-null  object
 6   Customer_Login_type  51290 non-null  object
 7   Product_Category     51290 non-null  object
 8   Product              51290 non-null  object
 9   Sales                51289 non-null  float64
 10  Quantity             51288 non-null  float64
 11  Discount             51289 non-null  float64
 12  Profit               51290 non-null  float64
 13  Shipping_Cost        51289 non-null  float64
 14  Order_Priority       51288 non-null  object
 15  Payment_method       51290 non-null  object
 16  sales_amount         51287 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 6.7+ MB

In [ ]:
sales_data["Gender"] = sales_data["Gender"].str[0]

In [ ]:
sales_data["Gender"].unique()

array(['M', 'F'], dtype=object)

In [ ]:
sales_data.columns = sales_data.columns.str.lower()

In [ ]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_date           51290 non-null  datetime64[ns]
 1   time                 51290 non-null  object
 2   aging                51289 non-null  float64
 3   customer_id          51290 non-null  int64
 4   gender               51290 non-null  object
 5   device_type          51290 non-null  object
 6   customer_login_type  51290 non-null  object
 7   product_category     51290 non-null  object
 8   product              51290 non-null  object
 9   sales                51289 non-null  float64
 10  quantity             51288 non-null  float64
 11  discount             51289 non-null  float64
 12  profit               51290 non-null  float64
 13  shipping_cost        51289 non-null  float64
 14  order_priority       51288 non-null  object
 15  payment_method       51290 non-null  object
 16  sales_amount         51287 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(8)
memory usage: 6.7+ MB

# Описова аналітика

- Яка максимальна та мінімальна сума продажу (sales_amount)? Яка сума продажу, середнє та медіана цього показника? Створи текстовий блок та запиши відповіді на ці запитання.
- Скільки категорій продукції продає компанія? Яка популярність кожної категорії? Створи текстові блоки та запиши відповіді на ці запитання.
Назви топ-5 популярних продуктів. Створи текстовий блок та запиши відповідь на це запитання.
- Хто купує частіше, жінки або чоловіки? Створи текстовий блок та запиши відповідь на це запитання.
- Який найбільш популярний метод оплати? Створи текстовий блок та запиши відповідь на це запитання.

In [ ]:
sales_data.describe()

,order_date,aging,customer_id,sales,quantity,discount,profit,shipping_cost,sales_amount
count,51290,51289.000000,51290.000000,51289.000000,51288.000000,51289.000000,51290.000000,51289.000000,51287.000000
mean,2018-07-24 02:43:35.163170304,5.255035,58155.758764,152.340872,2.502983,0.303821,70.407226,7.041557,382.864274
min,2018-01-01 00:03:33,1.000000,10000.000000,33.000000,1.000000,0.100000,0.500000,0.100000,33.000000
25%,2018-05-07 19:44:23,3.000000,35831.250000,85.000000,1.000000,0.200000,24.900000,2.500000,149.000000
50%,2018-07-28 09:29:51,5.000000,61018.000000,133.000000,2.000000,0.300000,59.900000,6.000000,248.000000
75%,2018-10-17 17:01:59.750000128,8.000000,80736.250000,218.000000,4.000000,0.400000,118.400000,11.800000,545.000000
max,2018-12-30 23:52:42,10.500000,99999.000000,250.000000,5.000000,0.500000,167.500000,16.800000,1250.000000
std,NaN,2.959948,26032.215826,66.495419,1.511859,0.131027,48.729488,4.871745,303.918182

- max = 1250.00
- min = 33.00
- sum = 19635960.00
- avg = 382.86
- медіана = 248.00

In [ ]:
sales_data["sales_amount"].sum()

np.float64(19635960.0)

In [ ]:
sales_data["sales_amount"].median()

248.0

- product_category count = 4
- Fashion = 50%; Home & Furniture = 30.1%; Auto & Accessories = 14.6%; Electronic = 5.3%
- Top 5 product: Suits, Jeans, T-Shirts, Fossil Watch, Shirts

In [ ]:
sales_data["product_category"].nunique()

4

In [ ]:
sales_data["product_category"].value_counts()

product_category
Fashion               25646
Home & Furniture      15438
Auto & Accessories     7505
Electronic             2701
Name: count, dtype: int64

In [ ]:
(sales_data["product"].value_counts()).head()

product
Suits           2332
Jeans           2332
T - Shirts      2332
Fossil Watch    2332
Shirts          2332
Name: count, dtype: int64

Хто купує частіше, жінки або чоловіки? Men

In [ ]:
sales_data["gender"].value_counts()

gender
M    28138
F    23152
Name: count, dtype: int64

Який найбільш популярний метод оплати? Credit_card

In [ ]:
sales_data["payment_method"].value_counts()

payment_method
credit_card    38137
money_order     9629
e_wallet        2789
debit_card       734
not_defined        1
Name: count, dtype: int64